# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# A- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(bb53486e-3749-4f08-a0c5-50582b780502)'
    subscriptionId: 'bb53486e-3749-4f08-a0c5-50582b780502'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DefaultResourceGroup-CUS'
    location: 'UK West'
    templateLocation: 'Linked artifact'
    csmFile: 'https://github.com/PiotrMichalski1987/rep1/blob/master/template.json'
    csmParametersFile: 'https://github.com/PiotrMichalski1987/rep1/blob/master/parameters.json'
    deploymentMode: 'Incremental'