trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script:
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(bb53486e-3749-4f08-a0c5-50582b780502)'
    subscriptionId: 'bb53486e-3749-4f08-a0c5-50582b780502'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DefaultResourceGroup-CUS'
    location: 'UK West'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/PiotrMichalski1987/rep1/master/template.json'
    #csmParametersFileLink: 'https://raw.githubusercontent.com/PiotrMichalski1987/rep1/master/parameters.json'
    deploymentMode: 'Validation'


